Data handling updates
jasp-stats/jaspBain pull request #145
Opened 2024-10-10 13:02 UTC by koenderks

2024-10-11 08:06 UTC, vandenman requested changes
looks good, some minor things below.

2024-10-11 10:39 UTC, koenderks commented on R/bainCommon.R
> +      if (any(grepl(pattern = " ", x = base::levels(dataset[, options[["fixedFactors"]]])))) {
Bain only allows for one factor per analysis

2024-10-11 10:39 UTC, koenderks commented on R/bainCommon.R
> +    dataset[factors] <- lapply(dataset[factors], as.factor)
If this is done in JASP automatically, then it is only for the unit tests yes

2024-10-11 11:23 UTC, vandenman commented on R/bainCommon.R
> +      if (any(grepl(pattern = " ", x = base::levels(dataset[, options[["fixedFactors"]]])))) {
sure, but if factor levels are encoded you never need to check for this anyway :)

2024-10-14 15:54 UTC, vandenman approved these changes

2024-10-14 15:54 UTC, merged